//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Ratify Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/deislabs/ratify/api/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CertificateStore)(nil), (*v1beta1.CertificateStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore(a.(*CertificateStore), b.(*v1beta1.CertificateStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CertificateStore)(nil), (*CertificateStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore(a.(*v1beta1.CertificateStore), b.(*CertificateStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateStoreList)(nil), (*v1beta1.CertificateStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateStoreList_To_v1beta1_CertificateStoreList(a.(*CertificateStoreList), b.(*v1beta1.CertificateStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CertificateStoreList)(nil), (*CertificateStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreList_To_v1alpha1_CertificateStoreList(a.(*v1beta1.CertificateStoreList), b.(*CertificateStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateStoreSpec)(nil), (*v1beta1.CertificateStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(a.(*CertificateStoreSpec), b.(*v1beta1.CertificateStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.CertificateStoreSpec)(nil), (*CertificateStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec(a.(*v1beta1.CertificateStoreSpec), b.(*CertificateStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PluginSource)(nil), (*v1beta1.PluginSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PluginSource_To_v1beta1_PluginSource(a.(*PluginSource), b.(*v1beta1.PluginSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PluginSource)(nil), (*PluginSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PluginSource_To_v1alpha1_PluginSource(a.(*v1beta1.PluginSource), b.(*PluginSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyList)(nil), (*v1beta1.PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicyList_To_v1beta1_PolicyList(a.(*PolicyList), b.(*v1beta1.PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PolicyList)(nil), (*PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicyList_To_v1alpha1_PolicyList(a.(*v1beta1.PolicyList), b.(*PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Store)(nil), (*v1beta1.Store)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Store_To_v1beta1_Store(a.(*Store), b.(*v1beta1.Store), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Store)(nil), (*Store)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Store_To_v1alpha1_Store(a.(*v1beta1.Store), b.(*Store), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreList)(nil), (*v1beta1.StoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreList_To_v1beta1_StoreList(a.(*StoreList), b.(*v1beta1.StoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.StoreList)(nil), (*StoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreList_To_v1alpha1_StoreList(a.(*v1beta1.StoreList), b.(*StoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreSpec)(nil), (*v1beta1.StoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec(a.(*StoreSpec), b.(*v1beta1.StoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.StoreSpec)(nil), (*StoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec(a.(*v1beta1.StoreSpec), b.(*StoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreStatus)(nil), (*v1beta1.StoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus(a.(*StoreStatus), b.(*v1beta1.StoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.StoreStatus)(nil), (*StoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus(a.(*v1beta1.StoreStatus), b.(*StoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Verifier)(nil), (*v1beta1.Verifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Verifier_To_v1beta1_Verifier(a.(*Verifier), b.(*v1beta1.Verifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Verifier)(nil), (*Verifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Verifier_To_v1alpha1_Verifier(a.(*v1beta1.Verifier), b.(*Verifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierList)(nil), (*v1beta1.VerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VerifierList_To_v1beta1_VerifierList(a.(*VerifierList), b.(*v1beta1.VerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VerifierList)(nil), (*VerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierList_To_v1alpha1_VerifierList(a.(*v1beta1.VerifierList), b.(*VerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierSpec)(nil), (*v1beta1.VerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec(a.(*VerifierSpec), b.(*v1beta1.VerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VerifierSpec)(nil), (*VerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec(a.(*v1beta1.VerifierSpec), b.(*VerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierStatus)(nil), (*v1beta1.VerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus(a.(*VerifierStatus), b.(*v1beta1.VerifierStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VerifierStatus)(nil), (*VerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus(a.(*v1beta1.VerifierStatus), b.(*VerifierStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*CertificateStoreStatus)(nil), (*v1beta1.CertificateStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(a.(*CertificateStoreStatus), b.(*v1beta1.CertificateStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PolicySpec)(nil), (*v1beta1.PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicySpec_To_v1beta1_PolicySpec(a.(*PolicySpec), b.(*v1beta1.PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*PolicyStatus)(nil), (*v1beta1.PolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicyStatus_To_v1beta1_PolicyStatus(a.(*PolicyStatus), b.(*v1beta1.PolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Policy)(nil), (*v1beta1.Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Policy_To_v1beta1_Policy(a.(*Policy), b.(*v1beta1.Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.CertificateStoreStatus)(nil), (*CertificateStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreStatus_To_v1alpha1_CertificateStoreStatus(a.(*v1beta1.CertificateStoreStatus), b.(*CertificateStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.PolicySpec)(nil), (*PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicySpec_To_v1alpha1_PolicySpec(a.(*v1beta1.PolicySpec), b.(*PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.PolicyStatus)(nil), (*PolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicyStatus_To_v1alpha1_PolicyStatus(a.(*v1beta1.PolicyStatus), b.(*PolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.Policy)(nil), (*Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Policy_To_v1alpha1_Policy(a.(*v1beta1.Policy), b.(*Policy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore(in *CertificateStore, out *v1beta1.CertificateStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore is an autogenerated conversion function.
func Convert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore(in *CertificateStore, out *v1beta1.CertificateStore, s conversion.Scope) error {
	return autoConvert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore(in, out, s)
}

func autoConvert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore(in *v1beta1.CertificateStore, out *CertificateStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CertificateStoreStatus_To_v1alpha1_CertificateStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore is an autogenerated conversion function.
func Convert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore(in *v1beta1.CertificateStore, out *CertificateStore, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore(in, out, s)
}

func autoConvert_v1alpha1_CertificateStoreList_To_v1beta1_CertificateStoreList(in *CertificateStoreList, out *v1beta1.CertificateStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.CertificateStore, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_CertificateStore_To_v1beta1_CertificateStore(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_CertificateStoreList_To_v1beta1_CertificateStoreList is an autogenerated conversion function.
func Convert_v1alpha1_CertificateStoreList_To_v1beta1_CertificateStoreList(in *CertificateStoreList, out *v1beta1.CertificateStoreList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CertificateStoreList_To_v1beta1_CertificateStoreList(in, out, s)
}

func autoConvert_v1beta1_CertificateStoreList_To_v1alpha1_CertificateStoreList(in *v1beta1.CertificateStoreList, out *CertificateStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateStore, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_CertificateStore_To_v1alpha1_CertificateStore(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_CertificateStoreList_To_v1alpha1_CertificateStoreList is an autogenerated conversion function.
func Convert_v1beta1_CertificateStoreList_To_v1alpha1_CertificateStoreList(in *v1beta1.CertificateStoreList, out *CertificateStoreList, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStoreList_To_v1alpha1_CertificateStoreList(in, out, s)
}

func autoConvert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in *CertificateStoreSpec, out *v1beta1.CertificateStoreSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec is an autogenerated conversion function.
func Convert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in *CertificateStoreSpec, out *v1beta1.CertificateStoreSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in, out, s)
}

func autoConvert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec(in *v1beta1.CertificateStoreSpec, out *CertificateStoreSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec is an autogenerated conversion function.
func Convert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec(in *v1beta1.CertificateStoreSpec, out *CertificateStoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStoreSpec_To_v1alpha1_CertificateStoreSpec(in, out, s)
}

func autoConvert_v1alpha1_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(in *CertificateStoreStatus, out *v1beta1.CertificateStoreStatus, s conversion.Scope) error {
	return nil
}

func autoConvert_v1beta1_CertificateStoreStatus_To_v1alpha1_CertificateStoreStatus(in *v1beta1.CertificateStoreStatus, out *CertificateStoreStatus, s conversion.Scope) error {
	// WARNING: in.IsSuccess requires manual conversion: does not exist in peer-type
	// WARNING: in.Error requires manual conversion: does not exist in peer-type
	// WARNING: in.BriefError requires manual conversion: does not exist in peer-type
	// WARNING: in.LastFetchedTime requires manual conversion: does not exist in peer-type
	// WARNING: in.Properties requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_PluginSource_To_v1beta1_PluginSource(in *PluginSource, out *v1beta1.PluginSource, s conversion.Scope) error {
	out.Artifact = in.Artifact
	out.AuthProvider = in.AuthProvider
	return nil
}

// Convert_v1alpha1_PluginSource_To_v1beta1_PluginSource is an autogenerated conversion function.
func Convert_v1alpha1_PluginSource_To_v1beta1_PluginSource(in *PluginSource, out *v1beta1.PluginSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_PluginSource_To_v1beta1_PluginSource(in, out, s)
}

func autoConvert_v1beta1_PluginSource_To_v1alpha1_PluginSource(in *v1beta1.PluginSource, out *PluginSource, s conversion.Scope) error {
	out.Artifact = in.Artifact
	out.AuthProvider = in.AuthProvider
	return nil
}

// Convert_v1beta1_PluginSource_To_v1alpha1_PluginSource is an autogenerated conversion function.
func Convert_v1beta1_PluginSource_To_v1alpha1_PluginSource(in *v1beta1.PluginSource, out *PluginSource, s conversion.Scope) error {
	return autoConvert_v1beta1_PluginSource_To_v1alpha1_PluginSource(in, out, s)
}

func autoConvert_v1alpha1_Policy_To_v1beta1_Policy(in *Policy, out *v1beta1.Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PolicySpec_To_v1beta1_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PolicyStatus_To_v1beta1_PolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Policy_To_v1alpha1_Policy(in *v1beta1.Policy, out *Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PolicySpec_To_v1alpha1_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PolicyStatus_To_v1alpha1_PolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PolicyList_To_v1beta1_PolicyList(in *PolicyList, out *v1beta1.PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Policy, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Policy_To_v1beta1_Policy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_PolicyList_To_v1beta1_PolicyList is an autogenerated conversion function.
func Convert_v1alpha1_PolicyList_To_v1beta1_PolicyList(in *PolicyList, out *v1beta1.PolicyList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PolicyList_To_v1beta1_PolicyList(in, out, s)
}

func autoConvert_v1beta1_PolicyList_To_v1alpha1_PolicyList(in *v1beta1.PolicyList, out *PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Policy_To_v1alpha1_Policy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_PolicyList_To_v1alpha1_PolicyList is an autogenerated conversion function.
func Convert_v1beta1_PolicyList_To_v1alpha1_PolicyList(in *v1beta1.PolicyList, out *PolicyList, s conversion.Scope) error {
	return autoConvert_v1beta1_PolicyList_To_v1alpha1_PolicyList(in, out, s)
}

func autoConvert_v1alpha1_PolicySpec_To_v1beta1_PolicySpec(in *PolicySpec, out *v1beta1.PolicySpec, s conversion.Scope) error {
	out.Parameters = in.Parameters
	return nil
}

func autoConvert_v1beta1_PolicySpec_To_v1alpha1_PolicySpec(in *v1beta1.PolicySpec, out *PolicySpec, s conversion.Scope) error {
	// WARNING: in.Type requires manual conversion: does not exist in peer-type
	out.Parameters = in.Parameters
	return nil
}

func autoConvert_v1alpha1_PolicyStatus_To_v1beta1_PolicyStatus(in *PolicyStatus, out *v1beta1.PolicyStatus, s conversion.Scope) error {
	return nil
}

func autoConvert_v1beta1_PolicyStatus_To_v1alpha1_PolicyStatus(in *v1beta1.PolicyStatus, out *PolicyStatus, s conversion.Scope) error {
	// WARNING: in.IsSuccess requires manual conversion: does not exist in peer-type
	// WARNING: in.Error requires manual conversion: does not exist in peer-type
	// WARNING: in.BriefError requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_Store_To_v1beta1_Store(in *Store, out *v1beta1.Store, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Store_To_v1beta1_Store is an autogenerated conversion function.
func Convert_v1alpha1_Store_To_v1beta1_Store(in *Store, out *v1beta1.Store, s conversion.Scope) error {
	return autoConvert_v1alpha1_Store_To_v1beta1_Store(in, out, s)
}

func autoConvert_v1beta1_Store_To_v1alpha1_Store(in *v1beta1.Store, out *Store, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Store_To_v1alpha1_Store is an autogenerated conversion function.
func Convert_v1beta1_Store_To_v1alpha1_Store(in *v1beta1.Store, out *Store, s conversion.Scope) error {
	return autoConvert_v1beta1_Store_To_v1alpha1_Store(in, out, s)
}

func autoConvert_v1alpha1_StoreList_To_v1beta1_StoreList(in *StoreList, out *v1beta1.StoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Store)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_StoreList_To_v1beta1_StoreList is an autogenerated conversion function.
func Convert_v1alpha1_StoreList_To_v1beta1_StoreList(in *StoreList, out *v1beta1.StoreList, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreList_To_v1beta1_StoreList(in, out, s)
}

func autoConvert_v1beta1_StoreList_To_v1alpha1_StoreList(in *v1beta1.StoreList, out *StoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Store)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_StoreList_To_v1alpha1_StoreList is an autogenerated conversion function.
func Convert_v1beta1_StoreList_To_v1alpha1_StoreList(in *v1beta1.StoreList, out *StoreList, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreList_To_v1alpha1_StoreList(in, out, s)
}

func autoConvert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec(in *StoreSpec, out *v1beta1.StoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Address = in.Address
	out.Source = (*v1beta1.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec is an autogenerated conversion function.
func Convert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec(in *StoreSpec, out *v1beta1.StoreSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreSpec_To_v1beta1_StoreSpec(in, out, s)
}

func autoConvert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec(in *v1beta1.StoreSpec, out *StoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec is an autogenerated conversion function.
func Convert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec(in *v1beta1.StoreSpec, out *StoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreSpec_To_v1alpha1_StoreSpec(in, out, s)
}

func autoConvert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus(in *StoreStatus, out *v1beta1.StoreStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus is an autogenerated conversion function.
func Convert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus(in *StoreStatus, out *v1beta1.StoreStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreStatus_To_v1beta1_StoreStatus(in, out, s)
}

func autoConvert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus(in *v1beta1.StoreStatus, out *StoreStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus is an autogenerated conversion function.
func Convert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus(in *v1beta1.StoreStatus, out *StoreStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreStatus_To_v1alpha1_StoreStatus(in, out, s)
}

func autoConvert_v1alpha1_Verifier_To_v1beta1_Verifier(in *Verifier, out *v1beta1.Verifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Verifier_To_v1beta1_Verifier is an autogenerated conversion function.
func Convert_v1alpha1_Verifier_To_v1beta1_Verifier(in *Verifier, out *v1beta1.Verifier, s conversion.Scope) error {
	return autoConvert_v1alpha1_Verifier_To_v1beta1_Verifier(in, out, s)
}

func autoConvert_v1beta1_Verifier_To_v1alpha1_Verifier(in *v1beta1.Verifier, out *Verifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Verifier_To_v1alpha1_Verifier is an autogenerated conversion function.
func Convert_v1beta1_Verifier_To_v1alpha1_Verifier(in *v1beta1.Verifier, out *Verifier, s conversion.Scope) error {
	return autoConvert_v1beta1_Verifier_To_v1alpha1_Verifier(in, out, s)
}

func autoConvert_v1alpha1_VerifierList_To_v1beta1_VerifierList(in *VerifierList, out *v1beta1.VerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Verifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VerifierList_To_v1beta1_VerifierList is an autogenerated conversion function.
func Convert_v1alpha1_VerifierList_To_v1beta1_VerifierList(in *VerifierList, out *v1beta1.VerifierList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VerifierList_To_v1beta1_VerifierList(in, out, s)
}

func autoConvert_v1beta1_VerifierList_To_v1alpha1_VerifierList(in *v1beta1.VerifierList, out *VerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Verifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VerifierList_To_v1alpha1_VerifierList is an autogenerated conversion function.
func Convert_v1beta1_VerifierList_To_v1alpha1_VerifierList(in *v1beta1.VerifierList, out *VerifierList, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierList_To_v1alpha1_VerifierList(in, out, s)
}

func autoConvert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec(in *VerifierSpec, out *v1beta1.VerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*v1beta1.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec is an autogenerated conversion function.
func Convert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec(in *VerifierSpec, out *v1beta1.VerifierSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VerifierSpec_To_v1beta1_VerifierSpec(in, out, s)
}

func autoConvert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec(in *v1beta1.VerifierSpec, out *VerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec is an autogenerated conversion function.
func Convert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec(in *v1beta1.VerifierSpec, out *VerifierSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierSpec_To_v1alpha1_VerifierSpec(in, out, s)
}

func autoConvert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus(in *VerifierStatus, out *v1beta1.VerifierStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus is an autogenerated conversion function.
func Convert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus(in *VerifierStatus, out *v1beta1.VerifierStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VerifierStatus_To_v1beta1_VerifierStatus(in, out, s)
}

func autoConvert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus(in *v1beta1.VerifierStatus, out *VerifierStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus is an autogenerated conversion function.
func Convert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus(in *v1beta1.VerifierStatus, out *VerifierStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierStatus_To_v1alpha1_VerifierStatus(in, out, s)
}
