# these files can be executed in VS Code with the `humao.rest-client` extension

POST http://localhost:6001/ratify/gatekeeper/v1/verify
Content-Type: application/json

{
  "apiVersion":"externaldata.gatekeeper.sh/v1alpha1",
  "kind":"ProviderRequest",
  "request": {
    "keys": [
      "wabbitnetworks.azurecr.io/test/net-monitor:signed",
      "wabbitnetworks.azurecr.io/test/net-monitor:unsigned"
    ]
  }
}
