//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Ratify Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	unversioned "github.com/ratify-project/ratify/api/unversioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CertificateStore)(nil), (*unversioned.CertificateStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStore_To_unversioned_CertificateStore(a.(*CertificateStore), b.(*unversioned.CertificateStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.CertificateStore)(nil), (*CertificateStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_CertificateStore_To_v1beta1_CertificateStore(a.(*unversioned.CertificateStore), b.(*CertificateStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateStoreList)(nil), (*unversioned.CertificateStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreList_To_unversioned_CertificateStoreList(a.(*CertificateStoreList), b.(*unversioned.CertificateStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.CertificateStoreList)(nil), (*CertificateStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_CertificateStoreList_To_v1beta1_CertificateStoreList(a.(*unversioned.CertificateStoreList), b.(*CertificateStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateStoreSpec)(nil), (*unversioned.CertificateStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec(a.(*CertificateStoreSpec), b.(*unversioned.CertificateStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.CertificateStoreSpec)(nil), (*CertificateStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(a.(*unversioned.CertificateStoreSpec), b.(*CertificateStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateStoreStatus)(nil), (*unversioned.CertificateStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus(a.(*CertificateStoreStatus), b.(*unversioned.CertificateStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.CertificateStoreStatus)(nil), (*CertificateStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(a.(*unversioned.CertificateStoreStatus), b.(*CertificateStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KeyManagementProvider)(nil), (*unversioned.KeyManagementProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KeyManagementProvider_To_unversioned_KeyManagementProvider(a.(*KeyManagementProvider), b.(*unversioned.KeyManagementProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.KeyManagementProvider)(nil), (*KeyManagementProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_KeyManagementProvider_To_v1beta1_KeyManagementProvider(a.(*unversioned.KeyManagementProvider), b.(*KeyManagementProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KeyManagementProviderList)(nil), (*unversioned.KeyManagementProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KeyManagementProviderList_To_unversioned_KeyManagementProviderList(a.(*KeyManagementProviderList), b.(*unversioned.KeyManagementProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.KeyManagementProviderList)(nil), (*KeyManagementProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_KeyManagementProviderList_To_v1beta1_KeyManagementProviderList(a.(*unversioned.KeyManagementProviderList), b.(*KeyManagementProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KeyManagementProviderSpec)(nil), (*unversioned.KeyManagementProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec(a.(*KeyManagementProviderSpec), b.(*unversioned.KeyManagementProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.KeyManagementProviderSpec)(nil), (*KeyManagementProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec(a.(*unversioned.KeyManagementProviderSpec), b.(*KeyManagementProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KeyManagementProviderStatus)(nil), (*unversioned.KeyManagementProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus(a.(*KeyManagementProviderStatus), b.(*unversioned.KeyManagementProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.KeyManagementProviderStatus)(nil), (*KeyManagementProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus(a.(*unversioned.KeyManagementProviderStatus), b.(*KeyManagementProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedKeyManagementProvider)(nil), (*unversioned.NamespacedKeyManagementProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedKeyManagementProvider_To_unversioned_NamespacedKeyManagementProvider(a.(*NamespacedKeyManagementProvider), b.(*unversioned.NamespacedKeyManagementProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedKeyManagementProvider)(nil), (*NamespacedKeyManagementProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedKeyManagementProvider_To_v1beta1_NamespacedKeyManagementProvider(a.(*unversioned.NamespacedKeyManagementProvider), b.(*NamespacedKeyManagementProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedKeyManagementProviderList)(nil), (*unversioned.NamespacedKeyManagementProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedKeyManagementProviderList_To_unversioned_NamespacedKeyManagementProviderList(a.(*NamespacedKeyManagementProviderList), b.(*unversioned.NamespacedKeyManagementProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedKeyManagementProviderList)(nil), (*NamespacedKeyManagementProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedKeyManagementProviderList_To_v1beta1_NamespacedKeyManagementProviderList(a.(*unversioned.NamespacedKeyManagementProviderList), b.(*NamespacedKeyManagementProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedKeyManagementProviderSpec)(nil), (*unversioned.NamespacedKeyManagementProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec(a.(*NamespacedKeyManagementProviderSpec), b.(*unversioned.NamespacedKeyManagementProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedKeyManagementProviderSpec)(nil), (*NamespacedKeyManagementProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec(a.(*unversioned.NamespacedKeyManagementProviderSpec), b.(*NamespacedKeyManagementProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedKeyManagementProviderStatus)(nil), (*unversioned.NamespacedKeyManagementProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus(a.(*NamespacedKeyManagementProviderStatus), b.(*unversioned.NamespacedKeyManagementProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedKeyManagementProviderStatus)(nil), (*NamespacedKeyManagementProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus(a.(*unversioned.NamespacedKeyManagementProviderStatus), b.(*NamespacedKeyManagementProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedPolicy)(nil), (*unversioned.NamespacedPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedPolicy_To_unversioned_NamespacedPolicy(a.(*NamespacedPolicy), b.(*unversioned.NamespacedPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedPolicy)(nil), (*NamespacedPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedPolicy_To_v1beta1_NamespacedPolicy(a.(*unversioned.NamespacedPolicy), b.(*NamespacedPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedPolicyList)(nil), (*unversioned.NamespacedPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedPolicyList_To_unversioned_NamespacedPolicyList(a.(*NamespacedPolicyList), b.(*unversioned.NamespacedPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedPolicyList)(nil), (*NamespacedPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedPolicyList_To_v1beta1_NamespacedPolicyList(a.(*unversioned.NamespacedPolicyList), b.(*NamespacedPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedPolicySpec)(nil), (*unversioned.NamespacedPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec(a.(*NamespacedPolicySpec), b.(*unversioned.NamespacedPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedPolicySpec)(nil), (*NamespacedPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec(a.(*unversioned.NamespacedPolicySpec), b.(*NamespacedPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedPolicyStatus)(nil), (*unversioned.NamespacedPolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus(a.(*NamespacedPolicyStatus), b.(*unversioned.NamespacedPolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedPolicyStatus)(nil), (*NamespacedPolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus(a.(*unversioned.NamespacedPolicyStatus), b.(*NamespacedPolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedStore)(nil), (*unversioned.NamespacedStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedStore_To_unversioned_NamespacedStore(a.(*NamespacedStore), b.(*unversioned.NamespacedStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedStore)(nil), (*NamespacedStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedStore_To_v1beta1_NamespacedStore(a.(*unversioned.NamespacedStore), b.(*NamespacedStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedStoreList)(nil), (*unversioned.NamespacedStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedStoreList_To_unversioned_NamespacedStoreList(a.(*NamespacedStoreList), b.(*unversioned.NamespacedStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedStoreList)(nil), (*NamespacedStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedStoreList_To_v1beta1_NamespacedStoreList(a.(*unversioned.NamespacedStoreList), b.(*NamespacedStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedStoreSpec)(nil), (*unversioned.NamespacedStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec(a.(*NamespacedStoreSpec), b.(*unversioned.NamespacedStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedStoreSpec)(nil), (*NamespacedStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec(a.(*unversioned.NamespacedStoreSpec), b.(*NamespacedStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedStoreStatus)(nil), (*unversioned.NamespacedStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus(a.(*NamespacedStoreStatus), b.(*unversioned.NamespacedStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedStoreStatus)(nil), (*NamespacedStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus(a.(*unversioned.NamespacedStoreStatus), b.(*NamespacedStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedVerifier)(nil), (*unversioned.NamespacedVerifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedVerifier_To_unversioned_NamespacedVerifier(a.(*NamespacedVerifier), b.(*unversioned.NamespacedVerifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedVerifier)(nil), (*NamespacedVerifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedVerifier_To_v1beta1_NamespacedVerifier(a.(*unversioned.NamespacedVerifier), b.(*NamespacedVerifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedVerifierList)(nil), (*unversioned.NamespacedVerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedVerifierList_To_unversioned_NamespacedVerifierList(a.(*NamespacedVerifierList), b.(*unversioned.NamespacedVerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedVerifierList)(nil), (*NamespacedVerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedVerifierList_To_v1beta1_NamespacedVerifierList(a.(*unversioned.NamespacedVerifierList), b.(*NamespacedVerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedVerifierSpec)(nil), (*unversioned.NamespacedVerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec(a.(*NamespacedVerifierSpec), b.(*unversioned.NamespacedVerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedVerifierSpec)(nil), (*NamespacedVerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec(a.(*unversioned.NamespacedVerifierSpec), b.(*NamespacedVerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedVerifierStatus)(nil), (*unversioned.NamespacedVerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus(a.(*NamespacedVerifierStatus), b.(*unversioned.NamespacedVerifierStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.NamespacedVerifierStatus)(nil), (*NamespacedVerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus(a.(*unversioned.NamespacedVerifierStatus), b.(*NamespacedVerifierStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PluginSource)(nil), (*unversioned.PluginSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PluginSource_To_unversioned_PluginSource(a.(*PluginSource), b.(*unversioned.PluginSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.PluginSource)(nil), (*PluginSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_PluginSource_To_v1beta1_PluginSource(a.(*unversioned.PluginSource), b.(*PluginSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Policy)(nil), (*unversioned.Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Policy_To_unversioned_Policy(a.(*Policy), b.(*unversioned.Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.Policy)(nil), (*Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_Policy_To_v1beta1_Policy(a.(*unversioned.Policy), b.(*Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyList)(nil), (*unversioned.PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicyList_To_unversioned_PolicyList(a.(*PolicyList), b.(*unversioned.PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.PolicyList)(nil), (*PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_PolicyList_To_v1beta1_PolicyList(a.(*unversioned.PolicyList), b.(*PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicySpec)(nil), (*unversioned.PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicySpec_To_unversioned_PolicySpec(a.(*PolicySpec), b.(*unversioned.PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.PolicySpec)(nil), (*PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_PolicySpec_To_v1beta1_PolicySpec(a.(*unversioned.PolicySpec), b.(*PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyStatus)(nil), (*unversioned.PolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus(a.(*PolicyStatus), b.(*unversioned.PolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.PolicyStatus)(nil), (*PolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus(a.(*unversioned.PolicyStatus), b.(*PolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Store)(nil), (*unversioned.Store)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Store_To_unversioned_Store(a.(*Store), b.(*unversioned.Store), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.Store)(nil), (*Store)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_Store_To_v1beta1_Store(a.(*unversioned.Store), b.(*Store), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreList)(nil), (*unversioned.StoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreList_To_unversioned_StoreList(a.(*StoreList), b.(*unversioned.StoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.StoreList)(nil), (*StoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_StoreList_To_v1beta1_StoreList(a.(*unversioned.StoreList), b.(*StoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreSpec)(nil), (*unversioned.StoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreSpec_To_unversioned_StoreSpec(a.(*StoreSpec), b.(*unversioned.StoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.StoreSpec)(nil), (*StoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_StoreSpec_To_v1beta1_StoreSpec(a.(*unversioned.StoreSpec), b.(*StoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreStatus)(nil), (*unversioned.StoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StoreStatus_To_unversioned_StoreStatus(a.(*StoreStatus), b.(*unversioned.StoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.StoreStatus)(nil), (*StoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_StoreStatus_To_v1beta1_StoreStatus(a.(*unversioned.StoreStatus), b.(*StoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Verifier)(nil), (*unversioned.Verifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Verifier_To_unversioned_Verifier(a.(*Verifier), b.(*unversioned.Verifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.Verifier)(nil), (*Verifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_Verifier_To_v1beta1_Verifier(a.(*unversioned.Verifier), b.(*Verifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierList)(nil), (*unversioned.VerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierList_To_unversioned_VerifierList(a.(*VerifierList), b.(*unversioned.VerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.VerifierList)(nil), (*VerifierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_VerifierList_To_v1beta1_VerifierList(a.(*unversioned.VerifierList), b.(*VerifierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierSpec)(nil), (*unversioned.VerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec(a.(*VerifierSpec), b.(*unversioned.VerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.VerifierSpec)(nil), (*VerifierSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec(a.(*unversioned.VerifierSpec), b.(*VerifierSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerifierStatus)(nil), (*unversioned.VerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus(a.(*VerifierStatus), b.(*unversioned.VerifierStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.VerifierStatus)(nil), (*VerifierStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus(a.(*unversioned.VerifierStatus), b.(*VerifierStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_CertificateStore_To_unversioned_CertificateStore(in *CertificateStore, out *unversioned.CertificateStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_CertificateStore_To_unversioned_CertificateStore is an autogenerated conversion function.
func Convert_v1beta1_CertificateStore_To_unversioned_CertificateStore(in *CertificateStore, out *unversioned.CertificateStore, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStore_To_unversioned_CertificateStore(in, out, s)
}

func autoConvert_unversioned_CertificateStore_To_v1beta1_CertificateStore(in *unversioned.CertificateStore, out *CertificateStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_CertificateStore_To_v1beta1_CertificateStore is an autogenerated conversion function.
func Convert_unversioned_CertificateStore_To_v1beta1_CertificateStore(in *unversioned.CertificateStore, out *CertificateStore, s conversion.Scope) error {
	return autoConvert_unversioned_CertificateStore_To_v1beta1_CertificateStore(in, out, s)
}

func autoConvert_v1beta1_CertificateStoreList_To_unversioned_CertificateStoreList(in *CertificateStoreList, out *unversioned.CertificateStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.CertificateStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_CertificateStoreList_To_unversioned_CertificateStoreList is an autogenerated conversion function.
func Convert_v1beta1_CertificateStoreList_To_unversioned_CertificateStoreList(in *CertificateStoreList, out *unversioned.CertificateStoreList, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStoreList_To_unversioned_CertificateStoreList(in, out, s)
}

func autoConvert_unversioned_CertificateStoreList_To_v1beta1_CertificateStoreList(in *unversioned.CertificateStoreList, out *CertificateStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CertificateStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_CertificateStoreList_To_v1beta1_CertificateStoreList is an autogenerated conversion function.
func Convert_unversioned_CertificateStoreList_To_v1beta1_CertificateStoreList(in *unversioned.CertificateStoreList, out *CertificateStoreList, s conversion.Scope) error {
	return autoConvert_unversioned_CertificateStoreList_To_v1beta1_CertificateStoreList(in, out, s)
}

func autoConvert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec(in *CertificateStoreSpec, out *unversioned.CertificateStoreSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec is an autogenerated conversion function.
func Convert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec(in *CertificateStoreSpec, out *unversioned.CertificateStoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStoreSpec_To_unversioned_CertificateStoreSpec(in, out, s)
}

func autoConvert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in *unversioned.CertificateStoreSpec, out *CertificateStoreSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec is an autogenerated conversion function.
func Convert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in *unversioned.CertificateStoreSpec, out *CertificateStoreSpec, s conversion.Scope) error {
	return autoConvert_unversioned_CertificateStoreSpec_To_v1beta1_CertificateStoreSpec(in, out, s)
}

func autoConvert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus(in *CertificateStoreStatus, out *unversioned.CertificateStoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus is an autogenerated conversion function.
func Convert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus(in *CertificateStoreStatus, out *unversioned.CertificateStoreStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStoreStatus_To_unversioned_CertificateStoreStatus(in, out, s)
}

func autoConvert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(in *unversioned.CertificateStoreStatus, out *CertificateStoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus is an autogenerated conversion function.
func Convert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(in *unversioned.CertificateStoreStatus, out *CertificateStoreStatus, s conversion.Scope) error {
	return autoConvert_unversioned_CertificateStoreStatus_To_v1beta1_CertificateStoreStatus(in, out, s)
}

func autoConvert_v1beta1_KeyManagementProvider_To_unversioned_KeyManagementProvider(in *KeyManagementProvider, out *unversioned.KeyManagementProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_KeyManagementProvider_To_unversioned_KeyManagementProvider is an autogenerated conversion function.
func Convert_v1beta1_KeyManagementProvider_To_unversioned_KeyManagementProvider(in *KeyManagementProvider, out *unversioned.KeyManagementProvider, s conversion.Scope) error {
	return autoConvert_v1beta1_KeyManagementProvider_To_unversioned_KeyManagementProvider(in, out, s)
}

func autoConvert_unversioned_KeyManagementProvider_To_v1beta1_KeyManagementProvider(in *unversioned.KeyManagementProvider, out *KeyManagementProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_KeyManagementProvider_To_v1beta1_KeyManagementProvider is an autogenerated conversion function.
func Convert_unversioned_KeyManagementProvider_To_v1beta1_KeyManagementProvider(in *unversioned.KeyManagementProvider, out *KeyManagementProvider, s conversion.Scope) error {
	return autoConvert_unversioned_KeyManagementProvider_To_v1beta1_KeyManagementProvider(in, out, s)
}

func autoConvert_v1beta1_KeyManagementProviderList_To_unversioned_KeyManagementProviderList(in *KeyManagementProviderList, out *unversioned.KeyManagementProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.KeyManagementProvider)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_KeyManagementProviderList_To_unversioned_KeyManagementProviderList is an autogenerated conversion function.
func Convert_v1beta1_KeyManagementProviderList_To_unversioned_KeyManagementProviderList(in *KeyManagementProviderList, out *unversioned.KeyManagementProviderList, s conversion.Scope) error {
	return autoConvert_v1beta1_KeyManagementProviderList_To_unversioned_KeyManagementProviderList(in, out, s)
}

func autoConvert_unversioned_KeyManagementProviderList_To_v1beta1_KeyManagementProviderList(in *unversioned.KeyManagementProviderList, out *KeyManagementProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]KeyManagementProvider)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_KeyManagementProviderList_To_v1beta1_KeyManagementProviderList is an autogenerated conversion function.
func Convert_unversioned_KeyManagementProviderList_To_v1beta1_KeyManagementProviderList(in *unversioned.KeyManagementProviderList, out *KeyManagementProviderList, s conversion.Scope) error {
	return autoConvert_unversioned_KeyManagementProviderList_To_v1beta1_KeyManagementProviderList(in, out, s)
}

func autoConvert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec(in *KeyManagementProviderSpec, out *unversioned.KeyManagementProviderSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec is an autogenerated conversion function.
func Convert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec(in *KeyManagementProviderSpec, out *unversioned.KeyManagementProviderSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_KeyManagementProviderSpec_To_unversioned_KeyManagementProviderSpec(in, out, s)
}

func autoConvert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec(in *unversioned.KeyManagementProviderSpec, out *KeyManagementProviderSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec is an autogenerated conversion function.
func Convert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec(in *unversioned.KeyManagementProviderSpec, out *KeyManagementProviderSpec, s conversion.Scope) error {
	return autoConvert_unversioned_KeyManagementProviderSpec_To_v1beta1_KeyManagementProviderSpec(in, out, s)
}

func autoConvert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus(in *KeyManagementProviderStatus, out *unversioned.KeyManagementProviderStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus is an autogenerated conversion function.
func Convert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus(in *KeyManagementProviderStatus, out *unversioned.KeyManagementProviderStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_KeyManagementProviderStatus_To_unversioned_KeyManagementProviderStatus(in, out, s)
}

func autoConvert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus(in *unversioned.KeyManagementProviderStatus, out *KeyManagementProviderStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus is an autogenerated conversion function.
func Convert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus(in *unversioned.KeyManagementProviderStatus, out *KeyManagementProviderStatus, s conversion.Scope) error {
	return autoConvert_unversioned_KeyManagementProviderStatus_To_v1beta1_KeyManagementProviderStatus(in, out, s)
}

func autoConvert_v1beta1_NamespacedKeyManagementProvider_To_unversioned_NamespacedKeyManagementProvider(in *NamespacedKeyManagementProvider, out *unversioned.NamespacedKeyManagementProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_NamespacedKeyManagementProvider_To_unversioned_NamespacedKeyManagementProvider is an autogenerated conversion function.
func Convert_v1beta1_NamespacedKeyManagementProvider_To_unversioned_NamespacedKeyManagementProvider(in *NamespacedKeyManagementProvider, out *unversioned.NamespacedKeyManagementProvider, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedKeyManagementProvider_To_unversioned_NamespacedKeyManagementProvider(in, out, s)
}

func autoConvert_unversioned_NamespacedKeyManagementProvider_To_v1beta1_NamespacedKeyManagementProvider(in *unversioned.NamespacedKeyManagementProvider, out *NamespacedKeyManagementProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_NamespacedKeyManagementProvider_To_v1beta1_NamespacedKeyManagementProvider is an autogenerated conversion function.
func Convert_unversioned_NamespacedKeyManagementProvider_To_v1beta1_NamespacedKeyManagementProvider(in *unversioned.NamespacedKeyManagementProvider, out *NamespacedKeyManagementProvider, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedKeyManagementProvider_To_v1beta1_NamespacedKeyManagementProvider(in, out, s)
}

func autoConvert_v1beta1_NamespacedKeyManagementProviderList_To_unversioned_NamespacedKeyManagementProviderList(in *NamespacedKeyManagementProviderList, out *unversioned.NamespacedKeyManagementProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.NamespacedKeyManagementProvider)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_NamespacedKeyManagementProviderList_To_unversioned_NamespacedKeyManagementProviderList is an autogenerated conversion function.
func Convert_v1beta1_NamespacedKeyManagementProviderList_To_unversioned_NamespacedKeyManagementProviderList(in *NamespacedKeyManagementProviderList, out *unversioned.NamespacedKeyManagementProviderList, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedKeyManagementProviderList_To_unversioned_NamespacedKeyManagementProviderList(in, out, s)
}

func autoConvert_unversioned_NamespacedKeyManagementProviderList_To_v1beta1_NamespacedKeyManagementProviderList(in *unversioned.NamespacedKeyManagementProviderList, out *NamespacedKeyManagementProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NamespacedKeyManagementProvider)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_NamespacedKeyManagementProviderList_To_v1beta1_NamespacedKeyManagementProviderList is an autogenerated conversion function.
func Convert_unversioned_NamespacedKeyManagementProviderList_To_v1beta1_NamespacedKeyManagementProviderList(in *unversioned.NamespacedKeyManagementProviderList, out *NamespacedKeyManagementProviderList, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedKeyManagementProviderList_To_v1beta1_NamespacedKeyManagementProviderList(in, out, s)
}

func autoConvert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec(in *NamespacedKeyManagementProviderSpec, out *unversioned.NamespacedKeyManagementProviderSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec is an autogenerated conversion function.
func Convert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec(in *NamespacedKeyManagementProviderSpec, out *unversioned.NamespacedKeyManagementProviderSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedKeyManagementProviderSpec_To_unversioned_NamespacedKeyManagementProviderSpec(in, out, s)
}

func autoConvert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec(in *unversioned.NamespacedKeyManagementProviderSpec, out *NamespacedKeyManagementProviderSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec is an autogenerated conversion function.
func Convert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec(in *unversioned.NamespacedKeyManagementProviderSpec, out *NamespacedKeyManagementProviderSpec, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedKeyManagementProviderSpec_To_v1beta1_NamespacedKeyManagementProviderSpec(in, out, s)
}

func autoConvert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus(in *NamespacedKeyManagementProviderStatus, out *unversioned.NamespacedKeyManagementProviderStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus is an autogenerated conversion function.
func Convert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus(in *NamespacedKeyManagementProviderStatus, out *unversioned.NamespacedKeyManagementProviderStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedKeyManagementProviderStatus_To_unversioned_NamespacedKeyManagementProviderStatus(in, out, s)
}

func autoConvert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus(in *unversioned.NamespacedKeyManagementProviderStatus, out *NamespacedKeyManagementProviderStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	out.LastFetchedTime = (*v1.Time)(unsafe.Pointer(in.LastFetchedTime))
	out.Properties = in.Properties
	return nil
}

// Convert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus is an autogenerated conversion function.
func Convert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus(in *unversioned.NamespacedKeyManagementProviderStatus, out *NamespacedKeyManagementProviderStatus, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedKeyManagementProviderStatus_To_v1beta1_NamespacedKeyManagementProviderStatus(in, out, s)
}

func autoConvert_v1beta1_NamespacedPolicy_To_unversioned_NamespacedPolicy(in *NamespacedPolicy, out *unversioned.NamespacedPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_NamespacedPolicy_To_unversioned_NamespacedPolicy is an autogenerated conversion function.
func Convert_v1beta1_NamespacedPolicy_To_unversioned_NamespacedPolicy(in *NamespacedPolicy, out *unversioned.NamespacedPolicy, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedPolicy_To_unversioned_NamespacedPolicy(in, out, s)
}

func autoConvert_unversioned_NamespacedPolicy_To_v1beta1_NamespacedPolicy(in *unversioned.NamespacedPolicy, out *NamespacedPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_NamespacedPolicy_To_v1beta1_NamespacedPolicy is an autogenerated conversion function.
func Convert_unversioned_NamespacedPolicy_To_v1beta1_NamespacedPolicy(in *unversioned.NamespacedPolicy, out *NamespacedPolicy, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedPolicy_To_v1beta1_NamespacedPolicy(in, out, s)
}

func autoConvert_v1beta1_NamespacedPolicyList_To_unversioned_NamespacedPolicyList(in *NamespacedPolicyList, out *unversioned.NamespacedPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.NamespacedPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_NamespacedPolicyList_To_unversioned_NamespacedPolicyList is an autogenerated conversion function.
func Convert_v1beta1_NamespacedPolicyList_To_unversioned_NamespacedPolicyList(in *NamespacedPolicyList, out *unversioned.NamespacedPolicyList, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedPolicyList_To_unversioned_NamespacedPolicyList(in, out, s)
}

func autoConvert_unversioned_NamespacedPolicyList_To_v1beta1_NamespacedPolicyList(in *unversioned.NamespacedPolicyList, out *NamespacedPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NamespacedPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_NamespacedPolicyList_To_v1beta1_NamespacedPolicyList is an autogenerated conversion function.
func Convert_unversioned_NamespacedPolicyList_To_v1beta1_NamespacedPolicyList(in *unversioned.NamespacedPolicyList, out *NamespacedPolicyList, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedPolicyList_To_v1beta1_NamespacedPolicyList(in, out, s)
}

func autoConvert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec(in *NamespacedPolicySpec, out *unversioned.NamespacedPolicySpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec is an autogenerated conversion function.
func Convert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec(in *NamespacedPolicySpec, out *unversioned.NamespacedPolicySpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedPolicySpec_To_unversioned_NamespacedPolicySpec(in, out, s)
}

func autoConvert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec(in *unversioned.NamespacedPolicySpec, out *NamespacedPolicySpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec is an autogenerated conversion function.
func Convert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec(in *unversioned.NamespacedPolicySpec, out *NamespacedPolicySpec, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedPolicySpec_To_v1beta1_NamespacedPolicySpec(in, out, s)
}

func autoConvert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus(in *NamespacedPolicyStatus, out *unversioned.NamespacedPolicyStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus is an autogenerated conversion function.
func Convert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus(in *NamespacedPolicyStatus, out *unversioned.NamespacedPolicyStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedPolicyStatus_To_unversioned_NamespacedPolicyStatus(in, out, s)
}

func autoConvert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus(in *unversioned.NamespacedPolicyStatus, out *NamespacedPolicyStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus is an autogenerated conversion function.
func Convert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus(in *unversioned.NamespacedPolicyStatus, out *NamespacedPolicyStatus, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedPolicyStatus_To_v1beta1_NamespacedPolicyStatus(in, out, s)
}

func autoConvert_v1beta1_NamespacedStore_To_unversioned_NamespacedStore(in *NamespacedStore, out *unversioned.NamespacedStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_NamespacedStore_To_unversioned_NamespacedStore is an autogenerated conversion function.
func Convert_v1beta1_NamespacedStore_To_unversioned_NamespacedStore(in *NamespacedStore, out *unversioned.NamespacedStore, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedStore_To_unversioned_NamespacedStore(in, out, s)
}

func autoConvert_unversioned_NamespacedStore_To_v1beta1_NamespacedStore(in *unversioned.NamespacedStore, out *NamespacedStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_NamespacedStore_To_v1beta1_NamespacedStore is an autogenerated conversion function.
func Convert_unversioned_NamespacedStore_To_v1beta1_NamespacedStore(in *unversioned.NamespacedStore, out *NamespacedStore, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedStore_To_v1beta1_NamespacedStore(in, out, s)
}

func autoConvert_v1beta1_NamespacedStoreList_To_unversioned_NamespacedStoreList(in *NamespacedStoreList, out *unversioned.NamespacedStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.NamespacedStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_NamespacedStoreList_To_unversioned_NamespacedStoreList is an autogenerated conversion function.
func Convert_v1beta1_NamespacedStoreList_To_unversioned_NamespacedStoreList(in *NamespacedStoreList, out *unversioned.NamespacedStoreList, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedStoreList_To_unversioned_NamespacedStoreList(in, out, s)
}

func autoConvert_unversioned_NamespacedStoreList_To_v1beta1_NamespacedStoreList(in *unversioned.NamespacedStoreList, out *NamespacedStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NamespacedStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_NamespacedStoreList_To_v1beta1_NamespacedStoreList is an autogenerated conversion function.
func Convert_unversioned_NamespacedStoreList_To_v1beta1_NamespacedStoreList(in *unversioned.NamespacedStoreList, out *NamespacedStoreList, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedStoreList_To_v1beta1_NamespacedStoreList(in, out, s)
}

func autoConvert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec(in *NamespacedStoreSpec, out *unversioned.NamespacedStoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Address = in.Address
	out.Source = (*unversioned.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec is an autogenerated conversion function.
func Convert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec(in *NamespacedStoreSpec, out *unversioned.NamespacedStoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedStoreSpec_To_unversioned_NamespacedStoreSpec(in, out, s)
}

func autoConvert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec(in *unversioned.NamespacedStoreSpec, out *NamespacedStoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec is an autogenerated conversion function.
func Convert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec(in *unversioned.NamespacedStoreSpec, out *NamespacedStoreSpec, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedStoreSpec_To_v1beta1_NamespacedStoreSpec(in, out, s)
}

func autoConvert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus(in *NamespacedStoreStatus, out *unversioned.NamespacedStoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus is an autogenerated conversion function.
func Convert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus(in *NamespacedStoreStatus, out *unversioned.NamespacedStoreStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedStoreStatus_To_unversioned_NamespacedStoreStatus(in, out, s)
}

func autoConvert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus(in *unversioned.NamespacedStoreStatus, out *NamespacedStoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus is an autogenerated conversion function.
func Convert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus(in *unversioned.NamespacedStoreStatus, out *NamespacedStoreStatus, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedStoreStatus_To_v1beta1_NamespacedStoreStatus(in, out, s)
}

func autoConvert_v1beta1_NamespacedVerifier_To_unversioned_NamespacedVerifier(in *NamespacedVerifier, out *unversioned.NamespacedVerifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_NamespacedVerifier_To_unversioned_NamespacedVerifier is an autogenerated conversion function.
func Convert_v1beta1_NamespacedVerifier_To_unversioned_NamespacedVerifier(in *NamespacedVerifier, out *unversioned.NamespacedVerifier, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedVerifier_To_unversioned_NamespacedVerifier(in, out, s)
}

func autoConvert_unversioned_NamespacedVerifier_To_v1beta1_NamespacedVerifier(in *unversioned.NamespacedVerifier, out *NamespacedVerifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_NamespacedVerifier_To_v1beta1_NamespacedVerifier is an autogenerated conversion function.
func Convert_unversioned_NamespacedVerifier_To_v1beta1_NamespacedVerifier(in *unversioned.NamespacedVerifier, out *NamespacedVerifier, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedVerifier_To_v1beta1_NamespacedVerifier(in, out, s)
}

func autoConvert_v1beta1_NamespacedVerifierList_To_unversioned_NamespacedVerifierList(in *NamespacedVerifierList, out *unversioned.NamespacedVerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.NamespacedVerifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_NamespacedVerifierList_To_unversioned_NamespacedVerifierList is an autogenerated conversion function.
func Convert_v1beta1_NamespacedVerifierList_To_unversioned_NamespacedVerifierList(in *NamespacedVerifierList, out *unversioned.NamespacedVerifierList, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedVerifierList_To_unversioned_NamespacedVerifierList(in, out, s)
}

func autoConvert_unversioned_NamespacedVerifierList_To_v1beta1_NamespacedVerifierList(in *unversioned.NamespacedVerifierList, out *NamespacedVerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NamespacedVerifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_NamespacedVerifierList_To_v1beta1_NamespacedVerifierList is an autogenerated conversion function.
func Convert_unversioned_NamespacedVerifierList_To_v1beta1_NamespacedVerifierList(in *unversioned.NamespacedVerifierList, out *NamespacedVerifierList, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedVerifierList_To_v1beta1_NamespacedVerifierList(in, out, s)
}

func autoConvert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec(in *NamespacedVerifierSpec, out *unversioned.NamespacedVerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*unversioned.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec is an autogenerated conversion function.
func Convert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec(in *NamespacedVerifierSpec, out *unversioned.NamespacedVerifierSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedVerifierSpec_To_unversioned_NamespacedVerifierSpec(in, out, s)
}

func autoConvert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec(in *unversioned.NamespacedVerifierSpec, out *NamespacedVerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec is an autogenerated conversion function.
func Convert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec(in *unversioned.NamespacedVerifierSpec, out *NamespacedVerifierSpec, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedVerifierSpec_To_v1beta1_NamespacedVerifierSpec(in, out, s)
}

func autoConvert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus(in *NamespacedVerifierStatus, out *unversioned.NamespacedVerifierStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus is an autogenerated conversion function.
func Convert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus(in *NamespacedVerifierStatus, out *unversioned.NamespacedVerifierStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespacedVerifierStatus_To_unversioned_NamespacedVerifierStatus(in, out, s)
}

func autoConvert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus(in *unversioned.NamespacedVerifierStatus, out *NamespacedVerifierStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus is an autogenerated conversion function.
func Convert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus(in *unversioned.NamespacedVerifierStatus, out *NamespacedVerifierStatus, s conversion.Scope) error {
	return autoConvert_unversioned_NamespacedVerifierStatus_To_v1beta1_NamespacedVerifierStatus(in, out, s)
}

func autoConvert_v1beta1_PluginSource_To_unversioned_PluginSource(in *PluginSource, out *unversioned.PluginSource, s conversion.Scope) error {
	out.Artifact = in.Artifact
	out.AuthProvider = in.AuthProvider
	return nil
}

// Convert_v1beta1_PluginSource_To_unversioned_PluginSource is an autogenerated conversion function.
func Convert_v1beta1_PluginSource_To_unversioned_PluginSource(in *PluginSource, out *unversioned.PluginSource, s conversion.Scope) error {
	return autoConvert_v1beta1_PluginSource_To_unversioned_PluginSource(in, out, s)
}

func autoConvert_unversioned_PluginSource_To_v1beta1_PluginSource(in *unversioned.PluginSource, out *PluginSource, s conversion.Scope) error {
	out.Artifact = in.Artifact
	out.AuthProvider = in.AuthProvider
	return nil
}

// Convert_unversioned_PluginSource_To_v1beta1_PluginSource is an autogenerated conversion function.
func Convert_unversioned_PluginSource_To_v1beta1_PluginSource(in *unversioned.PluginSource, out *PluginSource, s conversion.Scope) error {
	return autoConvert_unversioned_PluginSource_To_v1beta1_PluginSource(in, out, s)
}

func autoConvert_v1beta1_Policy_To_unversioned_Policy(in *Policy, out *unversioned.Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PolicySpec_To_unversioned_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Policy_To_unversioned_Policy is an autogenerated conversion function.
func Convert_v1beta1_Policy_To_unversioned_Policy(in *Policy, out *unversioned.Policy, s conversion.Scope) error {
	return autoConvert_v1beta1_Policy_To_unversioned_Policy(in, out, s)
}

func autoConvert_unversioned_Policy_To_v1beta1_Policy(in *unversioned.Policy, out *Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_PolicySpec_To_v1beta1_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_Policy_To_v1beta1_Policy is an autogenerated conversion function.
func Convert_unversioned_Policy_To_v1beta1_Policy(in *unversioned.Policy, out *Policy, s conversion.Scope) error {
	return autoConvert_unversioned_Policy_To_v1beta1_Policy(in, out, s)
}

func autoConvert_v1beta1_PolicyList_To_unversioned_PolicyList(in *PolicyList, out *unversioned.PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.Policy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_PolicyList_To_unversioned_PolicyList is an autogenerated conversion function.
func Convert_v1beta1_PolicyList_To_unversioned_PolicyList(in *PolicyList, out *unversioned.PolicyList, s conversion.Scope) error {
	return autoConvert_v1beta1_PolicyList_To_unversioned_PolicyList(in, out, s)
}

func autoConvert_unversioned_PolicyList_To_v1beta1_PolicyList(in *unversioned.PolicyList, out *PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Policy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_PolicyList_To_v1beta1_PolicyList is an autogenerated conversion function.
func Convert_unversioned_PolicyList_To_v1beta1_PolicyList(in *unversioned.PolicyList, out *PolicyList, s conversion.Scope) error {
	return autoConvert_unversioned_PolicyList_To_v1beta1_PolicyList(in, out, s)
}

func autoConvert_v1beta1_PolicySpec_To_unversioned_PolicySpec(in *PolicySpec, out *unversioned.PolicySpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_PolicySpec_To_unversioned_PolicySpec is an autogenerated conversion function.
func Convert_v1beta1_PolicySpec_To_unversioned_PolicySpec(in *PolicySpec, out *unversioned.PolicySpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PolicySpec_To_unversioned_PolicySpec(in, out, s)
}

func autoConvert_unversioned_PolicySpec_To_v1beta1_PolicySpec(in *unversioned.PolicySpec, out *PolicySpec, s conversion.Scope) error {
	out.Type = in.Type
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_PolicySpec_To_v1beta1_PolicySpec is an autogenerated conversion function.
func Convert_unversioned_PolicySpec_To_v1beta1_PolicySpec(in *unversioned.PolicySpec, out *PolicySpec, s conversion.Scope) error {
	return autoConvert_unversioned_PolicySpec_To_v1beta1_PolicySpec(in, out, s)
}

func autoConvert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus(in *PolicyStatus, out *unversioned.PolicyStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus is an autogenerated conversion function.
func Convert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus(in *PolicyStatus, out *unversioned.PolicyStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_PolicyStatus_To_unversioned_PolicyStatus(in, out, s)
}

func autoConvert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus(in *unversioned.PolicyStatus, out *PolicyStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus is an autogenerated conversion function.
func Convert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus(in *unversioned.PolicyStatus, out *PolicyStatus, s conversion.Scope) error {
	return autoConvert_unversioned_PolicyStatus_To_v1beta1_PolicyStatus(in, out, s)
}

func autoConvert_v1beta1_Store_To_unversioned_Store(in *Store, out *unversioned.Store, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_StoreSpec_To_unversioned_StoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_StoreStatus_To_unversioned_StoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Store_To_unversioned_Store is an autogenerated conversion function.
func Convert_v1beta1_Store_To_unversioned_Store(in *Store, out *unversioned.Store, s conversion.Scope) error {
	return autoConvert_v1beta1_Store_To_unversioned_Store(in, out, s)
}

func autoConvert_unversioned_Store_To_v1beta1_Store(in *unversioned.Store, out *Store, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_StoreSpec_To_v1beta1_StoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_StoreStatus_To_v1beta1_StoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_Store_To_v1beta1_Store is an autogenerated conversion function.
func Convert_unversioned_Store_To_v1beta1_Store(in *unversioned.Store, out *Store, s conversion.Scope) error {
	return autoConvert_unversioned_Store_To_v1beta1_Store(in, out, s)
}

func autoConvert_v1beta1_StoreList_To_unversioned_StoreList(in *StoreList, out *unversioned.StoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.Store)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_StoreList_To_unversioned_StoreList is an autogenerated conversion function.
func Convert_v1beta1_StoreList_To_unversioned_StoreList(in *StoreList, out *unversioned.StoreList, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreList_To_unversioned_StoreList(in, out, s)
}

func autoConvert_unversioned_StoreList_To_v1beta1_StoreList(in *unversioned.StoreList, out *StoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Store)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_StoreList_To_v1beta1_StoreList is an autogenerated conversion function.
func Convert_unversioned_StoreList_To_v1beta1_StoreList(in *unversioned.StoreList, out *StoreList, s conversion.Scope) error {
	return autoConvert_unversioned_StoreList_To_v1beta1_StoreList(in, out, s)
}

func autoConvert_v1beta1_StoreSpec_To_unversioned_StoreSpec(in *StoreSpec, out *unversioned.StoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Address = in.Address
	out.Source = (*unversioned.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_StoreSpec_To_unversioned_StoreSpec is an autogenerated conversion function.
func Convert_v1beta1_StoreSpec_To_unversioned_StoreSpec(in *StoreSpec, out *unversioned.StoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreSpec_To_unversioned_StoreSpec(in, out, s)
}

func autoConvert_unversioned_StoreSpec_To_v1beta1_StoreSpec(in *unversioned.StoreSpec, out *StoreSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_StoreSpec_To_v1beta1_StoreSpec is an autogenerated conversion function.
func Convert_unversioned_StoreSpec_To_v1beta1_StoreSpec(in *unversioned.StoreSpec, out *StoreSpec, s conversion.Scope) error {
	return autoConvert_unversioned_StoreSpec_To_v1beta1_StoreSpec(in, out, s)
}

func autoConvert_v1beta1_StoreStatus_To_unversioned_StoreStatus(in *StoreStatus, out *unversioned.StoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_StoreStatus_To_unversioned_StoreStatus is an autogenerated conversion function.
func Convert_v1beta1_StoreStatus_To_unversioned_StoreStatus(in *StoreStatus, out *unversioned.StoreStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_StoreStatus_To_unversioned_StoreStatus(in, out, s)
}

func autoConvert_unversioned_StoreStatus_To_v1beta1_StoreStatus(in *unversioned.StoreStatus, out *StoreStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_StoreStatus_To_v1beta1_StoreStatus is an autogenerated conversion function.
func Convert_unversioned_StoreStatus_To_v1beta1_StoreStatus(in *unversioned.StoreStatus, out *StoreStatus, s conversion.Scope) error {
	return autoConvert_unversioned_StoreStatus_To_v1beta1_StoreStatus(in, out, s)
}

func autoConvert_v1beta1_Verifier_To_unversioned_Verifier(in *Verifier, out *unversioned.Verifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Verifier_To_unversioned_Verifier is an autogenerated conversion function.
func Convert_v1beta1_Verifier_To_unversioned_Verifier(in *Verifier, out *unversioned.Verifier, s conversion.Scope) error {
	return autoConvert_v1beta1_Verifier_To_unversioned_Verifier(in, out, s)
}

func autoConvert_unversioned_Verifier_To_v1beta1_Verifier(in *unversioned.Verifier, out *Verifier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_Verifier_To_v1beta1_Verifier is an autogenerated conversion function.
func Convert_unversioned_Verifier_To_v1beta1_Verifier(in *unversioned.Verifier, out *Verifier, s conversion.Scope) error {
	return autoConvert_unversioned_Verifier_To_v1beta1_Verifier(in, out, s)
}

func autoConvert_v1beta1_VerifierList_To_unversioned_VerifierList(in *VerifierList, out *unversioned.VerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.Verifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VerifierList_To_unversioned_VerifierList is an autogenerated conversion function.
func Convert_v1beta1_VerifierList_To_unversioned_VerifierList(in *VerifierList, out *unversioned.VerifierList, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierList_To_unversioned_VerifierList(in, out, s)
}

func autoConvert_unversioned_VerifierList_To_v1beta1_VerifierList(in *unversioned.VerifierList, out *VerifierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Verifier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_VerifierList_To_v1beta1_VerifierList is an autogenerated conversion function.
func Convert_unversioned_VerifierList_To_v1beta1_VerifierList(in *unversioned.VerifierList, out *VerifierList, s conversion.Scope) error {
	return autoConvert_unversioned_VerifierList_To_v1beta1_VerifierList(in, out, s)
}

func autoConvert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec(in *VerifierSpec, out *unversioned.VerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*unversioned.PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec is an autogenerated conversion function.
func Convert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec(in *VerifierSpec, out *unversioned.VerifierSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierSpec_To_unversioned_VerifierSpec(in, out, s)
}

func autoConvert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec(in *unversioned.VerifierSpec, out *VerifierSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ArtifactTypes = in.ArtifactTypes
	out.Address = in.Address
	out.Source = (*PluginSource)(unsafe.Pointer(in.Source))
	out.Parameters = in.Parameters
	return nil
}

// Convert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec is an autogenerated conversion function.
func Convert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec(in *unversioned.VerifierSpec, out *VerifierSpec, s conversion.Scope) error {
	return autoConvert_unversioned_VerifierSpec_To_v1beta1_VerifierSpec(in, out, s)
}

func autoConvert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus(in *VerifierStatus, out *unversioned.VerifierStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus is an autogenerated conversion function.
func Convert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus(in *VerifierStatus, out *unversioned.VerifierStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_VerifierStatus_To_unversioned_VerifierStatus(in, out, s)
}

func autoConvert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus(in *unversioned.VerifierStatus, out *VerifierStatus, s conversion.Scope) error {
	out.IsSuccess = in.IsSuccess
	out.Error = in.Error
	out.BriefError = in.BriefError
	return nil
}

// Convert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus is an autogenerated conversion function.
func Convert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus(in *unversioned.VerifierStatus, out *VerifierStatus, s conversion.Scope) error {
	return autoConvert_unversioned_VerifierStatus_To_v1beta1_VerifierStatus(in, out, s)
}
